### ISSUE TITLE
After export, import doesn't seem to recognize the location of the data stored previously.

### ISSUE THREAD

**Issue by clement-tan-exa** [looker-open-source/looker_deployer#88]
Hi everyone, new to docker and looker deployer, I tried running this command below using docker, I have the `looker.ini` file and `Dockerfile` defined. 

`docker run -it ldeploy content export --env dev --ini ./looker.ini --debug --folders 24 --local-target ./clement/test/ `

But when i try to import, i encounter an error saying`./test/` file not found exception
<img width="425" alt="Screen Shot 2022-06-08 at 4 07 36 PM" src="https://user-images.githubusercontent.com/48925056/172732244-c6eb9999-4959-459a-97d2-fec5fad17259.png">

Currently running on 
`python` v3.7.3
`looker-deployer` v0.3.5
`gzr` v0.2.54

**Comment by ddaugherty** [comment]
Hello.   

I don't seem to be able to recreate this error but here are some suggestions. 

I noticed the -ini flag is set to ./looker.ini.    If you are using the sample Dockerfile, it would have copied that ini file to /app inside the container but otherwise, the error shown is: "No such file | directory:  ./clement/test/"  

If you are using the sample Dockerfile:

- Change ENTRYPOINT  to ["/bin/bash"] and build 
- Run the container (interactive) docker run -it [container  name]
- cd /app
- Run the Deployer commands from the container so you can inspect its file system to verify if the folder exists, etc. 

It also might be easier to debug if you install Deployer locally and forgo managing the ephemeral nature of the container's file system.

Lastly, if you are still having the issue, could you provide the Dockerfile you are using? 

Thanks. 
Daniel

**Comment by clement-tan-exa** [comment]
This is my current Dockerfile.

```
  1 FROM python:3.8-slim
  2 
  3 RUN apt update
  4 RUN apt -y install ruby ruby-dev
  5 RUN gem install gazer
  6 
  7 RUN apt -y install git
  8 RUN git clone https://github.com/looker-open-source/looker_deployer.git
  9 
 10 WORKDIR /looker_deployer
 11 
 12 COPY looker.ini .
 13 RUN pip install .
 14 
 15 ENTRYPOINT ["ldeploy"]
```

I am currently using `docker run ldeploy ...`

In order to store the pulled data, i created a volume and store the data for future push to other looker instance. And clean it up when it is not inused.

Let me know if this approach is a valid option.

Thanks,
Clement

**Comment by ddaugherty** [comment]
There seems like the way to go, especially if you might need for the exported content to live longer than the container.  


As far as the issue with 'file not found' ...   I assume that path is valid to the attached volume?   

Just as a test, maybe change the destination for --local-target to the current path i.e --local-target folder-export 
so we can rule out any path issue.  

Thanks. 
Daniel

**Comment by clement-tan-exa** [comment]
I see, I managed to solve the problem. Thanks for the guidance @ddaugherty.

**Comment by ddaugherty** [comment]
Great!  

Daniel
